name: publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 0" # Weekly
  workflow_dispatch: {}

env:
  REGISTRY: quay.io
  IMAGE_NAME: quay.io/krestomatio/fedora-coreos-k3s
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        release_channel: ["v1.29", "v1.30", "stable"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.release_channel }},enable=${{ github.event_name != 'schedule' }}
            type=schedule,pattern=weekly,enable=${{ github.event_name == 'schedule' }},prefix=${{ matrix.release_channel }}-
            type=sha
          labels: |
            quay.expires-after=${{ github.event_name == 'schedule' && '1y' || '3y' }}

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_IO_USER }}
          password: ${{ secrets.QUAY_IO_PASS }}

      - name: Build container image
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: true
          set: |
            release.args.INSTALL_K3S_CHANNEL=${{ matrix.release_channel }}
